version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    image: tajalislam/product
    build: .
    command: npm start
    # command: ["npm", "start"]
    volumes:
      - .:/app/backend
    ports:
      - "3001:3001"
    depends_on:
      - db

  # proxy:
  #   image: nginx:1.17
  #   restart: unless-stopped
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
